-- MinInfer registry — Supabase / Postgres mirror of the local SQLite schema.
--
-- Same shape as dr/store.py so `dr sync` is a straight copy and the same queries
-- run on both. Two deliberate differences from the SQLite DDL:
--
--   * surrogate `id` columns are `generated by default as identity`, so Postgres
--     reassigns them on each sync (nothing references them);
--   * the deployments -> weights foreign key is NOT declared. SQLite never
--     enforced it either, and a merged-away weights_id can leave an intentional
--     orphan that must not block a sync.

create table if not exists weights (
  weights_id       text primary key,
  display_name     text not null,
  hf_repo          text,
  hf_revision      text,
  family           text,
  params_b         double precision,
  arch             text,
  license          text,
  released_at      text,
  modalities       text default '[]',
  aliases          text default '[]',
  benchmark        text default '{}',
  benchmark_source text,
  first_seen       text default (now()::text),
  last_seen        text default (now()::text)
);

create table if not exists deployments (
  deploy_id         text primary key,
  weights_id        text not null,
  provider          text not null,
  provider_model_id text not null,
  context_window    integer,
  max_output        integer,
  quantization      text,
  price_in          double precision,
  price_out         double precision,
  price_cached_in   double precision,
  zero_price        integer default 0,
  free_variant      integer default 0,
  subscription      integer default 0,
  trial_credits     integer default 0,
  discount          double precision,
  caps              text default '{}',
  limits            text default '{}',
  limits_confirmed  integer default 0,
  uptime_1d         double precision,
  first_token_ms    double precision,
  throughput        double precision,
  status            text default 'live',
  status_reason     text,
  status_changed_at text,
  status_source     text default 'source',
  pricing_state     text,
  source            text,
  source_url        text,
  first_seen        text default (now()::text),
  last_seen         text default (now()::text)
);
create index if not exists idx_dep_weights  on deployments(weights_id);
create index if not exists idx_dep_provider on deployments(provider);
create index if not exists idx_dep_price    on deployments(price_in, price_out);

create table if not exists evidence (
  id           bigint generated by default as identity primary key,
  entity_kind  text not null,
  entity_id    text not null,
  field        text not null,
  value        text,
  source       text,
  url          text,
  fetched_at   text,
  confidence   double precision,
  observed_via text
);
create index if not exists idx_ev_entity on evidence(entity_kind, entity_id, field);

-- Append-only price observations. Mirrors the SQLite table in `mininfer/store.py`.
-- `raw_value` is text so the published token is preserved verbatim; `usd_per_mtok`
-- is the normalized value two sources may be compared on. Never updated.
create table if not exists pricing_evidence (
  id           bigint generated by default as identity primary key,
  deploy_id    text not null,
  weights_id   text not null,
  provider     text not null,
  kind         text not null,
  raw_value    text,
  raw_unit     text not null,
  usd_per_mtok double precision,
  pricing_type text not null,
  is_sentinel  integer not null default 0,
  source       text,
  url          text,
  observed_at  text not null,
  confidence   double precision
);
create index if not exists idx_pe_deploy  on pricing_evidence(deploy_id, kind, observed_at);
create index if not exists idx_pe_weights on pricing_evidence(weights_id, kind, observed_at);

-- The reconciler's decision (P2). Derived from pricing_evidence and re-derivable
-- with `fb reconcile`; stored rather than viewed because the algorithm compares a
-- deployment against its own history *and* against independent peers, which SQL
-- cannot express. `usd_per_mtok` is always one of the deployment's own
-- observations, never a peer statistic.
create table if not exists price_resolution (
  deploy_id     text not null,
  kind          text not null,
  usd_per_mtok  double precision,
  state         text not null,
  reason        text,
  source        text,
  observed_at   text,
  confidence    double precision,
  reference_median double precision,
  source_count  integer not null default 0,
  factor        double precision,
  reconciled_at text not null,
  primary key (deploy_id, kind)
);
create index if not exists idx_pr_state on price_resolution(state);

-- The anomaly log (P3). Mirrors the SQLite table in mininfer/store.py. One row
-- per incident: opened when the reconciler refuses or flags a price, refreshed
-- in place on each reconcile, closed when the price returns to canonical.
-- `anomaly_id` is text and content-derived because sync drops surrogate ids.
create table if not exists price_anomalies (
  anomaly_id     text primary key,
  deploy_id      text not null,
  weights_id     text,
  dimension      text not null,
  kind           text not null,
  severity       text not null,
  state          text not null,
  expected       double precision,
  observed       double precision,
  factor         double precision,
  source_count   integer not null default 0,
  resolved_value double precision,
  detail         text,
  evidence       text default '{}',
  status         text not null default 'open',
  opened_at      text not null,
  last_seen_at   text not null,
  resolved_at    text,
  resolution     text
);
create index if not exists idx_pa_status on price_anomalies(status, severity);
create index if not exists idx_pa_deploy on price_anomalies(deploy_id, kind);

-- The pricing state machine's history (P4). Append-only, one row per change.
create table if not exists pricing_transitions (
  transition_id text primary key,
  deploy_id     text not null,
  from_state    text,
  to_state      text not null,
  detected_at   text not null,
  price_in      double precision,
  price_out     double precision,
  evidence      text default '{}'
);
create index if not exists idx_pt_deploy on pricing_transitions(deploy_id, detected_at);

-- Effective-dated price beliefs (P6). Append-only; a row is written only when the
-- belief changes. `effective_to` is derived by the view below, not stored.
create table if not exists price_history (
  history_id     text primary key,
  deploy_id      text not null,
  kind           text not null,
  usd_per_mtok   double precision,
  state          text not null,
  reason         text,
  source         text,
  observed_at    text,
  confidence     double precision,
  effective_from text not null
);
create index if not exists idx_ph_deploy on price_history(deploy_id, kind, effective_from);

-- The session spend ledger. Also the per-tenant budget that `auth.py` scopes,
-- which is why it is mirrored: a tenant's spend has to survive the instance that
-- recorded it.
create table if not exists sessions (
  session_id      text primary key,
  calls           integer not null default 0,
  tokens_in       integer not null default 0,
  tokens_out      integer not null default 0,
  cost_usd        double precision not null default 0,
  -- Tool spend, split from model spend: a search costs ~$0.008 and a routed
  -- call on a free arm costs $0, so one number would hide the only line item
  -- that actually costs money.
  searches        integer not null default 0,
  search_cost_usd double precision not null default 0,
  tenant_id       text,
  first_seen      text default current_timestamp,
  last_seen       text default current_timestamp
);

-- A session transcript: the content, as opposed to the spend in `sessions`.
-- Bounded per session by the writer and only written for a *named* session; see
-- the SQLite DDL in `mininfer/store.py` for the full reasoning.
create table if not exists messages (
  id         bigint generated by default as identity primary key,
  session_id text not null,
  role       text not null,
  content    text not null,
  task       text,
  deploy_id  text,
  ts         text not null,
  meta       text default '{}'
);
create index if not exists idx_msg_session on messages(session_id, id);

-- Operator pins: the shortlist a user pushes to the top of a task's routing.
-- Present in the SQLite DDL from the start, but missing here, so a Postgres
-- registry had no such table — `push_model` could not work at all, and any
-- query joining it (the model explorer) raised UndefinedTable.
create table if not exists pushed_models (
  deploy_id  text primary key,
  task       text,
  ts         text default current_timestamp
);

-- Warm-tier probe results and operator-toggled runtime settings. Mirrored so a
-- registry that lives in Postgres keeps the same view of provider health and
-- the same portal toggle as the local SQLite file.
create table if not exists provider_health (
  provider   text primary key,
  status     text not null,
  detail     text,
  latency_ms double precision,
  n_models   integer,
  checked_at text not null
);

create table if not exists settings (
  key        text primary key,
  value      text not null,
  updated_at text default current_timestamp
);

create table if not exists snapshots (
  id          bigint generated by default as identity primary key,
  source      text,
  url         text,
  fetched_at  text,
  sha256      text unique,
  nbytes      integer,
  storage_uri text
);

create table if not exists quota_buckets (
  deploy_id     text not null,
  "window"      text not null,
  api_key_alias text not null default 'default',
  limit_n       integer,
  used_n        integer default 0,
  reset_at      text,
  source        text default 'configured',
  -- Provider-reported limits (P5). `limit_n` stays the configured policy; the
  -- effective headroom is the minimum of the two.
  observed_limit_n     integer,
  observed_remaining_n integer,
  observed_reset_at    text,
  observed_at          text,
  observed_confidence  double precision,
  updated_at    text default (now()::text),
  primary key (deploy_id, "window", api_key_alias)
);

create table if not exists observations (
  id           bigint generated by default as identity primary key,
  deploy_id    text not null,
  task         text not null,
  ts           text not null,
  ok           integer not null,
  error_class  text,
  latency_ms   double precision,
  tokens_in    integer,
  tokens_out   integer,
  cost_usd     double precision,
  signal_kind  text,
  signal_value double precision,
  meta         text default '{}',
  -- Which limit a 429 hit: rpm | rpd | tpm | concurrency | account | unknown.
  rate_limit_reason text,
  -- Which session and tenant the call belonged to; null for CLI/benchmark calls.
  session_id   text,
  tenant_id    text,
  -- The difficulty the routing decision was made under, so an outcome can be read
  -- per difficulty rather than averaged into one number per (deploy, task).
  effort       text
);
create index if not exists idx_obs on observations(deploy_id, task);

create table if not exists decisions (
  id         bigint generated by default as identity primary key,
  ts         text not null,
  task       text not null,
  policy     text,
  mode       text,
  chosen     text,
  candidates text,
  reason     text,
  tenant_id  text
);

create table if not exists quarantine (
  id        bigint generated by default as identity primary key,
  source    text,
  entity_id text,
  field     text,
  value     text,
  reason    text,
  seen_at   text default (now()::text)
);
create unique index if not exists idx_q_uniq
  on quarantine(source, entity_id, field, value, reason);

create table if not exists weight_aliases (
  alias_id     text primary key,
  canonical_id text not null,
  reason       text,
  confidence   double precision,
  created_at   text default (now()::text)
);

create or replace view weights_resolved as
select w.*, coalesce(a.canonical_id, w.weights_id) as resolved_id
from weights w left join weight_aliases a on a.alias_id = w.weights_id;

-- The price read-model: every deployment plus the reconciled state and
-- provenance of its price. The price is `deployments.price_*`, materialized by
-- `reconcile_prices`; this view answers *why* — source, time, confidence, and
-- whether the reconciler trusts it.
create or replace view deployments_priced as
select d.*,
       pin.usd_per_mtok  as price_in_canonical,
       pin.source        as price_in_source,
       pin.observed_at   as price_in_observed_at,
       pin.confidence    as price_in_confidence,
       pin.state         as price_in_state,
       pin.reason        as price_in_reason,
       pout.usd_per_mtok as price_out_canonical,
       pout.source       as price_out_source,
       pout.observed_at  as price_out_observed_at,
       pout.confidence   as price_out_confidence,
       pout.state        as price_out_state,
       pout.reason       as price_out_reason
from deployments d
left join price_resolution pin  on pin.deploy_id = d.deploy_id and pin.kind = 'input'
left join price_resolution pout on pout.deploy_id = d.deploy_id and pout.kind = 'output';

-- The belief timeline with its end derived. `effective_to is null` is the current
-- belief, so one view answers both "now" and "then".
create or replace view price_history_dated as
select h.*,
       lead(h.effective_from) over (
         partition by h.deploy_id, h.kind
         order by h.effective_from, h.history_id
       ) as effective_to
from price_history h;

create or replace view routing_stats as
select deploy_id, task,
       count(*)                                             as n_all,
       sum(case when counted then 1 else 0 end)             as n,
       sum(case when counted then ok else 0 end)            as wins,
       sum(case when counted then 0 else 1 end)             as n_infra,
       avg(case when ok=1 then latency_ms end)              as mean_latency_ms,
       sum(case when error_class='429' then 1 else 0 end)   as n_429,
       sum(case when error_class='timeout' then 1 else 0 end) as n_timeout,
       sum(coalesce(cost_usd,0))                            as total_cost_usd
from (
    select *,
           (error_class is null or not (
               error_class in ('auth_error','bad_deploy_id','network_error','no_api_key','no_candidates','tls_error')
           )) as counted
    from observations
) as obs group by deploy_id, task;

-- The model "form guide": an agent-written dossier per free deployment (core
-- competency, strengths, weaknesses, when to use). Written by `mi scout`, read by
-- the dashboard and `/v1/dossiers`. `facts` is the snapshot the dossier was
-- synthesised from. One row per arm: the same weights served by two hosts are
-- two different horses.
create table if not exists model_dossiers (
  deploy_id       text primary key,
  weights_id      text,
  display_name    text,
  provider        text,
  price_out       double precision,
  core_competency text,
  summary         text,
  warrior         text,
  story           text,
  strengths       text default '[]',
  weaknesses      text default '[]',
  when_to_use     text default '[]',
  when_not_to_use text default '[]',
  best_for        text default '[]',
  search_sources  text default '[]',
  facts           text default '{}',
  confidence      double precision,
  generated_at    text,
  foreign key (deploy_id) references deployments(deploy_id)
);
create index if not exists idx_dossiers_generated on model_dossiers(generated_at);

-- Per-tenant daily search count, the "birthright" quota. A calendar-day bucket
-- because the free providers reset on a day (UTC for the structured tier).
-- `tenant_id` is 'local' when access control is off. Primary key (tenant, day).
create table if not exists search_usage_daily (
  tenant_id  text not null,
  day        text not null,
  searches   integer not null default 0,
  cost_usd   double precision not null default 0,
  updated_at text default CURRENT_TIMESTAMP,
  primary key (tenant_id, day)
);
